Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manager_host = true

  #DB vm
  config.vm.define "db" do |db|
  db.vm.box = "eurolinux-vagrant/centos-stream-9"
  db.vm.box_version = "9.0.48"
  db.vm.hostname = "database"
  db.vm.network "private_network", ip: "192.168.56.50"
  db.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    end
end

# mc (mem cache) vm
config.vm.define "mc" do |mc|
  mc.vm.box = "eurolinux-vagrant/centos-stream-9"
  mc.vm.box_version = "9.0.48"
  mc.vm.hostname = "memcache"
  mc.vm.network "private_network", ip: "192.168.56.51"
  mc.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
end
end

#rabbitmq vm
config.vm.define "rmq" do |rmq|
  rmq.vm.box = "eurolinux-vagrant/centos-stream-9"
  rmq.vm.box_version = "9.0.48"
  rmq.vm.hostname = "rabbitmq"
  rmq.vm.network "private_network", ip: "192.168.56.52"
  rmq.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
end
end

# tomcat vm
config.vm.define "tc" do |tc|
  tc.vm.box = "eurolinux-vagrant/centos-stream-9"
  tc.vm.box_version = "9.0.48"
  tc.vm.hostname = "tomcat"
  tc.vm.network "private_network", ip: "192.168.56.53"
  tc.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
end
end

# Nginx vm
config.vm.define "Ng" do |ng|
  ng.vm.box = "ubuntu/jammy64"
  ng.vm.hostname = "Nginx"
  ng.vm.network "private_network", ip: "192.168.56.54"
  ng.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "512"
end
end

end

